openapi: 3.0.2
info:
  title: PR Reviewer Assignment Service
  version: 1.0.0

paths:
  /api/team/get/:
    get:
      tags:
      - Teams
      summary: Получить команду с участниками
      parameters:
      - $ref: '#/components/parameters/TeamNameQuery'
      responses:
        '200':
          description: Объект команды
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
              example:
                team_name: backend
                members:
                  - user_id: 1
                    username: Alice
                    is_active: true
                  - user_id: 2
                    username: Bob
                    is_active: true
        '404':
          description: Команда не найдена

  /api/users/getReview/:
    get:
      tags:
      - Users
      summary: Получить PR'ы, где пользователь назначен ревьювером
      parameters:
      - $ref: '#/components/parameters/UserIdQuery'
      responses:
        '200':
          description: Список PR'ов пользователя
          content:
            application/json:
              schema:
                type: object
                required:
                  - user_id
                  - pull_requests
                properties:
                  user_id:
                    type: string
                  pull_requests:
                    type: array
                    items:
                      $ref: '#/components/schemas/PullRequestShort'
              example:
                user_id: 1
                pull_requests:
                  - pull_request_id: 1
                    pull_request_name: Add search
                    author_id: 2
                    status: OPEN
        '404':
          description: Пользователь не найден

  /api/statisticsUser/:
    get:
      tags:
      - Statistics
      summary: Получить статистику пользователей
      responses:
        '200':
          description: Массив статистики пользователей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserStatistics'
              example:
              - user_id: 1
                username: "Misha"
                assignments_count: 7
              - user_id: 2
                username: "Dasha"
                assignments_count: 3

  /api/statisticsPR/:
    get:
      tags:
      - Statistics
      summary: Получить статистику pull requests
      responses:
        '200':
          description: Массив статистики PR
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PullRequestStatistics'
              example:
              - pull_request_id: 1
                pull_request_name: "Add search"
                reviewers_count: 2
              - pull_request_id: 2
                pull_request_name: "Delete search"
                reviewers_count: 2

  /api/team/add/:
    post:
      tags:
      - Teams
      summary: Создать команду с участниками
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
            example:
              team_name: payments
              members:
                - 
                  username: Alice
                  is_active: true
                - 
                  username: Bob
                  is_active: true
      responses:
        '201':
          description: Команда создана
          content:
            application/json:
              schema:
                type: object
                properties:
                  team:
                    $ref: '#/components/schemas/Team'
              example:
                team:
                  team_name: backend
                  members:
                    - user_id: 1
                      username: Alice
                      is_active: true
                    - user_id: 2
                      username: Bob
                      is_active: true
        '400':
          description: Команда уже существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: TEAM_EXISTS
                  message: team_name already exists

  /api/users/setIsActive/:
    post:
      tags:
      - Users
      summary: Установить флаг активности пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - is_active
              properties:
                user_id:
                  type: integer
                is_active:
                  type: boolean
            example:
              user_id: 1
              is_active: false
      responses:
        '200':
          description: Обновлённый пользователь
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
              example:
                user:
                  user_id: 1
                  username: Bob
                  team_name: backend
                  is_active: false
        '404':
          description: Пользователь не найден

  /api/pullRequest/create/:
    post:
      tags:
      - PullRequests
      summary: Создать PR и автоматически назначить до 2 ревьюверов из команды автора
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - pull_request_name
                - author_id
              properties:
                pull_request_id:
                  type: string
                pull_request_name:
                  type: string
                author_id:
                  type: integer
            example:
              pull_request_name: Add search
              author_id: 1
      responses:
        '201':
          description: PR создан
          content:
            application/json:
              schema:
                type: object
                properties:
                  pr:
                    $ref: '#/components/schemas/PullRequest'
              example:
                pr:
                  pull_request_id: 1
                  pull_request_name: Add search
                  author_id: 1
                  status: OPEN
                  assigned_reviewers:
                    - 2
                    - 3
        '404':
          description: Автор или команда не найдены
        '409':
          description: PR уже существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: PR_EXISTS
                  message: PR id already exists

  /api/pullRequest/merge/:
    post:
      tags:
      - PullRequests
      summary: Пометить PR как MERGED (идемпотентная операция)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - pull_request_id
              properties:
                pull_request_id:
                  type: integer
            example:
              pull_request_id: 1
      responses:
        '200':
          description: PR в состоянии MERGED
          content:
            application/json:
              schema:
                type: object
                properties:
                  pr:
                    $ref: '#/components/schemas/PullRequest'
              example:
                pr:
                  pull_request_id: 1
                  pull_request_name: Add search
                  author_id: 1
                  status: MERGED
                  assigned_reviewers:
                    - 2
                    - 3
                  mergedAt: 2025-10-24T12:34:56Z
        '404':
          description: PR не найден

  /api/pullRequest/reassign/:
    post:
      tags:
      - PullRequests
      summary: Переназначить конкретного ревьювера на другого из его команды
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - pull_request_id
                - old_user_id
              properties:
                pull_request_id:
                  type: string
                old_user_id:
                  type: string
            example:
              pull_request_id: 1
              old_user_id: 1
      responses:
        '200':
          description: Переназначение выполнено
          content:
            application/json:
              schema:
                type: object
                required:
                  - pr
                  - replaced_by
                properties:
                  pr:
                    $ref: '#/components/schemas/PullRequest'
                  replaced_by:
                    type: string
                    description: user_id нового ревьювера
              example:
                pr:
                  pull_request_id: 1
                  pull_request_name: Add search
                  author_id: 2
                  status: OPEN
                  assigned_reviewers:
                    - 3
                    - 4
                replaced_by: 3
        '404':
          description: PR или пользователь не найден
          
        '409':
          description: Нарушение доменных правил переназначения
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                merged:
                  summary: Нельзя менять после MERGED
                  value:
                    error:
                      code: PR_MERGED
                      message: cannot reassign on merged PR
                notAssigned:
                  summary: Пользователь не был назначен ревьювером
                  value:
                    error:
                      code: NOT_ASSIGNED
                      message: reviewer is not assigned to this PR
                noCandidate:
                  summary: Нет доступных кандидатов
                  value:
                    error:
                      code: NO_CANDIDATE
                      message: no active replacement candidate in team

components:
  parameters:
    TeamNameQuery:
      name: team_name
      in: query
      description: Название команды
      required: true
      schema:
        type: string
        maxLength: 128
    UserIdQuery:
      name: user_id
      in: query
      description: Идентификатор пользователя
      required: true
      schema:
        type: integer

  schemas:
    Team:
      type: object
      required:
        - team_name
        - members
      properties:
        team_name:
          type: string
          maxLength: 128
        members:
          type: array
          items:
            type: object
            required:
              - username
            properties:
              user_id:
                type: integer
                readOnly: true
              username:
                type: string
                maxLength: 128
              is_active:
                type: boolean

    User:
      type: object
      required:
        - user_id
        - username
        - team_name
        - is_active
      properties:
        user_id:
          type: integer
          readOnly: true
        username:
          type: string
          maxLength: 128
        team_name:
          type: string
        is_active:
          type: boolean

    UserTeam:
      type: object
      required:
        - username
      properties:
        user_id:
          type: integer
          readOnly: true
        username:
          type: string
          maxLength: 128
        team:
          type: string
          readOnly: true
        is_active:
          type: boolean

    PullRequest:
      type: object
      required:
        - pull_request_name
        - author_id
      properties:
        pull_request_id:
          type: integer
          readOnly: true
        pull_request_name:
          type: string
          maxLength: 128
        author_id:
          type: integer
        status:
          type: string
          enum:
            - OPEN
            - MERGED
          readOnly: true
        assigned_reviewers:
          type: array
          items:
            type: string
          readOnly: true
        mergedAt:
          type: string
          format: date-time
          readOnly: true

    PullRequestShort:
      type: object
      required:
        - pull_request_id
        - pull_request_name
        - author_id
        - status
      properties:
        pull_request_id:
          type: integer
        pull_request_name:
          type: string
        author_id:
          type: integer
        status:
          type: string
          enum:
            - OPEN
            - MERGED

    UserStatistics:
      type: object
      properties:
        user_id:
          type: integer
        username:
          type: string
        assignments_count:
          type: integer

    PullRequestStatistics:
      type: object
      properties:
        pull_request_id:
          type: integer
        pull_request_name:
          type: string
        reviewers_count:
          type: integer

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
            message:
              type: string
